codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 95%
        threshold: 1%
        base: auto
    patch:
      default:
        target: 90%
        threshold: 2%
    changes:
      default:
        branches:
          - main
          - develop

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "test/**/*"
  - "scripts/**/*"
  - "node_modules/**/*"
  - "*.config.js"
  - "*.config.ts"
